# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mavis < Formula
  desc "unconventional commit"
  homepage "https://github.com/kristofferahl/mavis"
  version "0.9.0"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kristofferahl/mavis/releases/download/v0.9.0/mavis_v0.9.0_darwin_amd64.zip"
      sha256 "98b8d68340ee89eb919d24f153048bedec9f2186c79f6f4534ca133a8eecacb2"

      def install
        bin.install 'mavis'
        output = Utils.safe_popen_read("#{bin}/mavis", 'completion', 'bash')
        (bash_completion/'mavis').write output
        output = Utils.safe_popen_read("#{bin}/mavis", 'completion', 'zsh')
        (zsh_completion/'_mavis').write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kristofferahl/mavis/releases/download/v0.9.0/mavis_v0.9.0_darwin_arm64.zip"
      sha256 "fb1b20782e9e504a8fd569bfcc2739f48105333db12f722fd628e09ae1d0ff09"

      def install
        bin.install 'mavis'
        output = Utils.safe_popen_read("#{bin}/mavis", 'completion', 'bash')
        (bash_completion/'mavis').write output
        output = Utils.safe_popen_read("#{bin}/mavis", 'completion', 'zsh')
        (zsh_completion/'_mavis').write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kristofferahl/mavis/releases/download/v0.9.0/mavis_v0.9.0_linux_amd64.tar.gz"
        sha256 "0246be933bdce9dfde33de96a33210c9ab5559c3b66b253040de4451486f64f7"

        def install
          bin.install 'mavis'
          output = Utils.safe_popen_read("#{bin}/mavis", 'completion', 'bash')
          (bash_completion/'mavis').write output
          output = Utils.safe_popen_read("#{bin}/mavis", 'completion', 'zsh')
          (zsh_completion/'_mavis').write output
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kristofferahl/mavis/releases/download/v0.9.0/mavis_v0.9.0_linux_arm64.tar.gz"
        sha256 "329b6bb10a03f1e734b776a1f1c53dcae515fcfb195a5b61a64886d17a481713"

        def install
          bin.install 'mavis'
          output = Utils.safe_popen_read("#{bin}/mavis", 'completion', 'bash')
          (bash_completion/'mavis').write output
          output = Utils.safe_popen_read("#{bin}/mavis", 'completion', 'zsh')
          (zsh_completion/'_mavis').write output
        end
      end
    end
  end
end
