# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mavis < Formula
  desc "unconventional commit"
  homepage "https://github.com/kristofferahl/mavis"
  version "0.9.1"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kristofferahl/mavis/releases/download/v0.9.1/mavis_v0.9.1_darwin_amd64.zip"
      sha256 "e3c847581d409dd1f343481b086827107c7972cee76e93f8795c22d40df14dc9"

      def install
        bin.install 'mavis'
        output = Utils.safe_popen_read("#{bin}/mavis", 'completion', 'bash')
        (bash_completion/'mavis').write output
        output = Utils.safe_popen_read("#{bin}/mavis", 'completion', 'zsh')
        (zsh_completion/'_mavis').write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kristofferahl/mavis/releases/download/v0.9.1/mavis_v0.9.1_darwin_arm64.zip"
      sha256 "6e3d86cf348957eccd329fa488b0219fd1f3a6fbc376a1fcce383f78b2be13e6"

      def install
        bin.install 'mavis'
        output = Utils.safe_popen_read("#{bin}/mavis", 'completion', 'bash')
        (bash_completion/'mavis').write output
        output = Utils.safe_popen_read("#{bin}/mavis", 'completion', 'zsh')
        (zsh_completion/'_mavis').write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kristofferahl/mavis/releases/download/v0.9.1/mavis_v0.9.1_linux_amd64.tar.gz"
        sha256 "b0df161cabab9dbde529e95691d6075a789734b067fb6babe69434db65e27e98"

        def install
          bin.install 'mavis'
          output = Utils.safe_popen_read("#{bin}/mavis", 'completion', 'bash')
          (bash_completion/'mavis').write output
          output = Utils.safe_popen_read("#{bin}/mavis", 'completion', 'zsh')
          (zsh_completion/'_mavis').write output
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kristofferahl/mavis/releases/download/v0.9.1/mavis_v0.9.1_linux_arm64.tar.gz"
        sha256 "73ab6635a9d869c3e227f921886d2fbf4bd7de878c124ef3b89d959d911ad184"

        def install
          bin.install 'mavis'
          output = Utils.safe_popen_read("#{bin}/mavis", 'completion', 'bash')
          (bash_completion/'mavis').write output
          output = Utils.safe_popen_read("#{bin}/mavis", 'completion', 'zsh')
          (zsh_completion/'_mavis').write output
        end
      end
    end
  end
end
