# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Say < Formula
  desc "Say hello"
  homepage "https://github.com/kristofferahl/say"
  version "0.0.1"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kristofferahl/say/releases/download/v0.0.1/say_v0.0.1_darwin_arm64.zip"
      sha256 "0cba4084b2c12d22c2983ac2ce119e46276e6800a86b330cdcfeeb09447006c8"

      def install
        bin.install 'say'
        output = Utils.safe_popen_read("#{bin}/say", 'completion', 'bash')
        (bash_completion/'say').write output
        output = Utils.safe_popen_read("#{bin}/say", 'completion', 'zsh')
        (zsh_completion/'_say').write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kristofferahl/say/releases/download/v0.0.1/say_v0.0.1_darwin_amd64.zip"
      sha256 "366cf10cef7f41432a9c89abf58b60f81c0fa94379fbc9f09fad663442bcf99b"

      def install
        bin.install 'say'
        output = Utils.safe_popen_read("#{bin}/say", 'completion', 'bash')
        (bash_completion/'say').write output
        output = Utils.safe_popen_read("#{bin}/say", 'completion', 'zsh')
        (zsh_completion/'_say').write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kristofferahl/say/releases/download/v0.0.1/say_v0.0.1_linux_amd64.tar.gz"
      sha256 "d6eb1174d252bc560e7af565cc535aa300dacae347e2313712547b4985b00b88"

      def install
        bin.install 'say'
        output = Utils.safe_popen_read("#{bin}/say", 'completion', 'bash')
        (bash_completion/'say').write output
        output = Utils.safe_popen_read("#{bin}/say", 'completion', 'zsh')
        (zsh_completion/'_say').write output
      end
    end
  end
end
